import assert from 'node:assert/strict';
import * as current from '../../packages/forecast/src/baseline';
import { runRateDaily, demandRateFor } from '../../packages/forecast/src/layered';
import * as original from '../../../_ref-wezesha-restock/lib/forecast/baseline';
const today = new Date('2026-10-05T00:00:00Z');
const date = (back: number) => new Date(+today-back*86400000);
const series = (n: number, quantity=1) => Array.from({length:n},(_,i)=>({date:date(i+1),quantity}));
const show = (name:string, data:unknown) => console.log(JSON.stringify({name,data}));
const steady = series(365);
show('steady', {current:runRateDaily(steady,today),originalMean:original.weightedDailyRateAdjusted(steady,today),originalMedian:original.weightedDailyRateMedian(steady,today)});
const spike=steady.map(p=>({...p, quantity:+p.date===+date(1)?100:p.quantity}));
show('single100unitDay', {current:runRateDaily(spike,today),originalMean:original.weightedDailyRateAdjusted(spike,today),originalMedian:original.weightedDailyRateMedian(spike,today)});
const gap=steady.filter(p=>!(+p.date>=+date(20)&&+p.date<=+date(11)));
show('tenDayInternalGap',{currentNoSnapshots:runRateDaily(gap,today),currentConfirmedInStock:runRateDaily(gap,today,[],undefined,date(365)),originalEmptyMask:original.weightedDailyRateCensored(gap,[],today),recentHeavyNoSnapshots:demandRateFor('recent_heavy',gap,today),recentHeavyConfirmedOut:demandRateFor('recent_heavy',gap,today,{stockoutDates:Array.from({length:10},(_,i)=>date(i+11))})});
show('productHistoryThreshold',{day59:runRateDaily(series(59),today),day60:runRateDaily(series(60),today)});
const intermittent=Array.from({length:26},(_,i)=>({date:date(1+i*14),quantity:1}));
show('fortnightlySeller',{current:runRateDaily(intermittent,today),originalMean:original.weightedDailyRateAdjusted(intermittent,today),originalMedian:original.weightedDailyRateMedian(intermittent,today)});
const allOut=Array.from({length:365},(_,i)=>date(i+1));
show('salesOnEmptySnapshotDays',{current:runRateDaily(steady,today,allOut,undefined,date(365)),original:original.weightedDailyRateCensored(steady,allOut,today)});
const future=[...steady,{date:date(-1),quantity:1000}];
show('futureRow',{current:runRateDaily(future,today),currentRawMean:current.weightedDailyRate(future,today),original:original.weightedDailyRateAdjusted(future,today)});
const lateOut=steady.filter(p=>+p.date<+date(200));
show('mostlyStockedOutMedian',{originalMean:original.weightedDailyRateCensored(lateOut,allOut.slice(0,200),today),originalMedian:original.weightedDailyRateMedianCensored(lateOut,allOut.slice(0,200),today)});
show('boundaryBuckets',{atAsOf:original.bucketTotals([{date:today,quantity:7}],today,7,7),sevenDaysAgo:original.bucketTotals([{date:date(7),quantity:7}],today,7,7)});
const sparse=Array.from({length:18},(_,i)=>({date:date(1+i*21),quantity:1}));
show('everyThreeWeekSeller',{originalMean:original.weightedDailyRateAdjusted(sparse,today),originalMedian:original.weightedDailyRateMedian(sparse,today)});
const multiChannel=[{date:date(1),quantity:1},{date:date(1),quantity:1}];
const out29=Array.from({length:29},(_,i)=>date(i+2));
show('twoChannelsOneSaleDay',{original:original.weightedDailyRateCensored(multiChannel,out29,today),current:current.weightedDailyRateCensored(multiChannel,out29,today)});
show('partialCoverage',{fullGapInference:runRateDaily(gap,today),tenantStartedBeforeHistoryButProductHasNoSnapshots:runRateDaily(gap,today,[],undefined,date(365)),coverageBeganMidGap:runRateDaily(gap,today,[],undefined,date(15))});
show('recentHeavyProvenFullStock',{rate:demandRateFor('recent_heavy',gap,today,{stockoutDates:[],snapshotsSince:date(365)}),correctObservedLast30:20/30});
const zeroFilled=steady.map(p=>({...p,quantity:+p.date>=+date(20)&&+p.date<=+date(11)?0:1}));
show('absentVersusExplicitZeroRows',{absent:runRateDaily(gap,today),explicitZeros:runRateDaily(zeroFilled,today)});
assert.equal(runRateDaily(steady,today),1);
assert.equal(runRateDaily(series(59),today),1);
assert.ok(runRateDaily(series(60),today)<0.74);
assert.equal(original.weightedDailyRateMedian(sparse,today),0);
assert.equal(original.weightedDailyRateMedianCensored(lateOut,allOut.slice(0,200),today),0);
assert.equal(demandRateFor('recent_heavy',gap,today,{stockoutDates:[],snapshotsSince:date(365)}),20/30);
assert.equal(runRateDaily(future,today),1);
console.log('Audit assertions passed (includes reproductions of known defects; not acceptance criteria).');
